#!/usr/bin/env python3
"""Validate a generated TES task against the GA4GH TES 1.1 schema.

The authoritative schema is the OpenAPI document published by the
task-execution-schemas repository; ``components.schemas.tesTask`` is
extracted from it and its ``#/components/schemas/`` references are
rewritten to ``#/$defs/`` so the fragment stands alone as a JSON Schema.

Beyond schema validity, tasks generated by BiocJobs are *submitted* to
``POST /tasks``, so two extra rules are checked: the required fields a
create-task request must carry, and the absence of the fields a TES
server owns (a client that sends them is out of contract even though the
schema tolerates them).

usage: validate-tes-task.py <openapi.yaml> <task.json> [<task.json> ...]
"""

import json
import sys

import jsonschema
import yaml

# Fields assigned by the server; a create-task request must not set them.
SERVER_OWNED = ("id", "state", "logs", "creation_time")


def rewrite_refs(node):
    """Repoint intra-document $refs at the $defs of the extracted schema."""
    if isinstance(node, dict):
        return {
            key: (
                value.replace("#/components/schemas/", "#/$defs/")
                if key == "$ref" and isinstance(value, str)
                else rewrite_refs(value)
            )
            for key, value in node.items()
        }
    if isinstance(node, list):
        return [rewrite_refs(item) for item in node]
    return node


def load_task_schema(openapi_path):
    with open(openapi_path, encoding="utf-8") as con:
        document = yaml.safe_load(con)
    schemas = document["components"]["schemas"]
    schema = rewrite_refs(schemas["tesTask"])
    schema["$defs"] = rewrite_refs(schemas)
    return schema


def check_create_task_rules(task):
    """Return a list of create-task contract violations."""
    problems = []
    for field in SERVER_OWNED:
        if field in task:
            problems.append(
                "server-owned field '%s' must not be sent by a client" % field
            )
    executors = task.get("executors")
    if not executors:
        problems.append("'executors' is required and must be non-empty")
        return problems
    for index, executor in enumerate(executors):
        for field in ("image", "command"):
            if not executor.get(field):
                problems.append(
                    "executors[%d].%s is required" % (index, field)
                )
    return problems


def main(argv):
    if len(argv) < 3:
        sys.stderr.write(__doc__.splitlines()[-1] + "\n")
        return 2
    schema = load_task_schema(argv[1])
    validator = jsonschema.Draft202012Validator(schema)
    failed = False
    for path in argv[2:]:
        with open(path, encoding="utf-8") as con:
            task = json.load(con)
        errors = sorted(validator.iter_errors(task), key=lambda e: e.path)
        problems = ["/".join(str(p) for p in error.path) + ": " + error.message
                    for error in errors]
        problems += check_create_task_rules(task)
        if problems:
            failed = True
            sys.stderr.write("%s: INVALID\n" % path)
            for problem in problems:
                sys.stderr.write("  - %s\n" % problem)
        else:
            print("%s: valid GA4GH TES 1.1 task" % path)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
