#!/usr/bin/env Rapp
#| name: DESeq2
#| title: 'Differential gene expression analysis based on the negative binomial distribution'
#| description: |
#|   Stub of the DESeq2 DESCRIPTION carrying only the fields
#|   BiocJobs reads at generation time (package name and version). In the
#|   real package, the two files under inst/biocjobs/ are simply added to the
#|   existing source tree; nothing else changes.

# Generated by BiocExecute::execCompile(); do not modify by hand.

switch(
  "",

  #| name: deseq2_differential_expression
  #| title: 'DESeq2 differential expression'
  #| description: 'Runs the canonical DESeq2 workflow on a raw count matrix: size factor and dispersion estimation, negative-binomial GLM fitting and a Wald test for one pairwise contrast, with optional independent pre-filtering and log2-fold-change shrinkage. Produces the per-gene results table, the median-of-ratios normalized counts, and an MA plot. [BiocJobs job ''deseq2-differential-expression'' of package DESeq2]'
  deseq2_differential_expression = {
    #| description: 'Raw count matrix Tab-separated matrix of raw (un-normalized) integer read counts: first column gene identifiers, one further column per sample. Do not supply TPM/FPKM or otherwise normalized values. Input file (tsv).'
    #| val_type: string
    counts <- ""

    #| description: 'Sample table Tab-separated sample annotation: first column sample identifiers matching the count matrix column names, one further column per covariate (e.g. condition, batch). Every variable used in the design formula must be a column of this table. Input file (tsv).'
    #| val_type: string
    coldata <- ""

    #| description: 'Differential expression results Per-gene table (baseMean, log2FoldChange, lfcSE, pvalue, padj, and stat for unshrunken results), ordered by adjusted p-value. Output file (tsv).'
    #| val_type: string
    results <- "results.tsv"

    #| description: 'Normalized counts Median-of-ratios normalized counts for all retained genes. Output file (tsv).'
    #| val_type: string
    normalized_counts <- "normalized_counts.tsv"

    #| description: 'MA plot Output file (pdf).'
    #| val_type: string
    ma_plot <- "ma_plot.pdf"

    #| description: 'Design formula R formula over sample table columns. Control for covariates by putting them first; the tested variable comes last (e.g. "~ batch + condition").'
    #| val_type: string
    design <- "~ condition"

    #| description: 'Factor to test Sample table column containing the tested condition. Required.'
    #| val_type: string
    contrast_factor <- NA_character_

    #| description: 'Treatment level (numerator) Level of the tested factor whose effect is reported. Required.'
    #| val_type: string
    contrast_numerator <- NA_character_

    #| description: 'Reference level (denominator) Baseline level the treatment is compared against. Required.'
    #| val_type: string
    contrast_denominator <- NA_character_

    #| description: 'FDR threshold (alpha) Significance cutoff used to optimize independent filtering. Set it to the adjusted p-value threshold you will actually use. Range: 0 to 1.'
    #| val_type: float
    alpha <- 0.1

    #| description: 'Log2 fold change shrinkage Shrinkage estimator applied to the reported log2 fold changes; "apeglm" is the recommended default, "none" reports maximum likelihood estimates. One of: apeglm, ashr, normal, none.'
    #| val_type: string
    shrinkage <- "apeglm"

    #| description: 'Pre-filter low-count genes Remove genes with insufficient counts before testing.'
    #| val_type: bool
    prefilter <- TRUE

    #| description: 'Pre-filter minimum count Range: 1 to Inf.'
    #| val_type: integer
    prefilter_min_count <- 10L

    #| description: 'Pre-filter minimum samples Keep genes with at least the minimum count in at least this many samples. 0 (default) means automatic: the size of the smallest group of the tested factor. Range: 0 to Inf.'
    #| val_type: integer
    prefilter_min_samples <- 0L

    ## Hand parsed values to the job; the specification drives
    ## validation, coercion, defaults and required checks.
    BiocJobs::execJob("DESeq2", "deseq2-differential-expression", values = list(
        counts = counts,
        coldata = coldata,
        results = results,
        normalized_counts = normalized_counts,
        ma_plot = ma_plot,
        design = design,
        contrast_factor = contrast_factor,
        contrast_numerator = contrast_numerator,
        contrast_denominator = contrast_denominator,
        alpha = alpha,
        shrinkage = shrinkage,
        prefilter = prefilter,
        prefilter_min_count = prefilter_min_count,
        prefilter_min_samples = prefilter_min_samples
    ))
  }
)
